config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get "up" => "rails/health#show", as: :rails_health_check
  get 'index', to: 'pages#index'
  get 'about', to: 'pages#about'
 
 
  resources :users, only: [:index, :show] do
      get 'posts', to: 'posts#index'
      get 'comments', to: 'comments#index'
      collection do
        get 'search'
      end
   end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :post
    belongs_to :comment
    has_many :tags
  
    validates :title, presence: true
    validates :url, presence: true
    validates :thumbnail_url, presence: true
  end
  

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    
  end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_one :address
  
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
      @user = User.find(params[:user_id])
      @comments = @user.comments
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
        @users = User.paginate(page: params[:page], per_page: 10)
      end
      
    
    def about
    end

    
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
      @user = User.find(params[:user_id])
      @posts = @user.posts
    end
  end
  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = if params[:search]
                   User.where("name LIKE ?", "%#{params[:search]}%")
                 else
                   User.all
                 end
    end

    def show
      @user = User.find(params[:id])
    end

    def search
        @user = User.find_by(name: params[:search])
        if @user
          render 'menu'
        else
          redirect_to users_path, notice: 'User not found.'
        end
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Body</th>
      <!-- Add more columns if needed -->
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.user.name %></td>
        <td><%= comment.body %></td>
        <!-- Add more columns if needed -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>Idp</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
    
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'custom' %>
      
      <!-- Bootstrap CSS -->
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

      <%= javascript_importmap_tags %>
  </head>

  <body>
        <nav class="nav-top">
        <ul>
          <li><%= link_to 'Home', index_path, class: 'nav-link' %></li>
          <li><%= link_to 'About', about_path, class: 'nav-link' %></li>
        </ul>
        </nav>

    <%= yield %>
  
  </body>

  </html>

app/views/pages/about.html.erb
<h1>About Our Data Sources</h1>

<p>We have fetched data from the following sources:</p>

<h2>Faker Gem</h2>
<p>The Faker gem is used to generate realistic sample data for our models.</p>

<h2>Existing Models</h2>
<p>We have utilized existing models to fetch associated data and populate our database with realistic data.</p>

app/views/pages/index.html.erb
<h1 class="heading-primary">Data Collection</h1>

<div class="container-custom">

  <%= form_with(url: search_users_path, method: :get) do |form| %>
    <%= form.text_field :search, placeholder: "Search by name..." %>
    <%= form.submit "Search" %>
    <% end %>

  <table class="table-custom">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to 'View Posts', user_posts_path(user), class: 'btn btn-primary btn-custom' %>
            <%= link_to 'View Comments', user_comments_path(user), class: 'btn btn-secondary btn-custom' %>
            <%= link_to 'Show More', user_path(user), class: 'btn btn-primary btn-custom' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @users %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Body</th>
      
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/menu.html.erb
<div class="user-menu">
  <h1>User Menu</h1>
  <div class="user-details">
    <p><strong>Name:</strong> <span class="user-name"><%= @user.name %></span></p>
    <p><strong>Email:</strong> <span class="user-email"><%= @user.email %></span></p>
  </div>

  <h2>Posts</h2>
  <div class="user-posts">
    <% @user.posts.each do |post| %>
      <div class="post">
        <h3 class="post-title"><%= post.title %></h3>
        <p class="post-body"><%= post.body %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-details">
  <h1>User Details</h1>
  <p><strong>Name:</strong> <%= @user.name %></p>
  <p><strong>Email:</strong> <%= @user.email %></p>
</div>

<div class="posts-section">
  <h2>Posts</h2>
  <% @user.posts.each do |post| %>
    <div class="post">
      <h3><%= post.title %></h3>
      <p><%= post.body %></p>
    </div>
  <% end %>
</div>

<div class="comments-section">
  <h2>Comments</h2>
  <% @user.comments.each do |comment| %>
    <div class="comment">
      <p><strong>Comment:</strong> <%= comment.body %></p>
    </div>
  <% end %>
</div>